_target_: tava.datasets.animal_loader.SubjectLoader

subject_id: Hare_male_full_RM
root_fp: "./data/animal/"
split: ???  # to be defined in the code
resize_factor: 1.0
color_bkgd_aug: "random"
num_rays: 1024
cache_n_repeat: 5
near: null
far: null
legacy: true

# parameters used by models
pose_latent_dim: 0
n_transforms: 35
world_dist: 0.1
cano_dist: 0.063